fix: added pnpm format:fix in pre-commit hook
tinyhttp/tinyhttp pull request #380
Opened 2023-05-06 18:41 UTC by aarontravass

As suggested in [this](https://github.com/tinyhttp/tinyhttp/pull/379#issuecomment-1537198782), `pnpm format:fix` is added husky pre-commit hook.

2023-05-07 18:11 UTC, aarontravass commented
Linked CONTRIBUTING.md in README.md and added fork as first step instead of clone

2023-05-08 08:59 UTC, talentlessguy commented on CONTRIBUTING.md
> +hub clone {your_github_username}/tinyhttp
`hub` is an outdated CLI, use `gh` instead

2023-05-08 09:07 UTC, talentlessguy requested changes

2023-05-08 09:07 UTC, talentlessguy commented on .huskyrc.json
> +    "pre-commit": "pnpm format:fix && pnpm format && pnpm lint && pnpm build && pnpm test",
there's no need to double run prettier

2023-05-08 16:25 UTC, talentlessguy commented
@aarontravass yes that's a good idea

2023-05-08 17:39 UTC, aarontravass commented
done

2023-05-08 17:43 UTC, talentlessguy commented
wait why do we need 16.12+? what tool require it?

2023-05-08 17:46 UTC, aarontravass commented
> wait why do we need 16.12+? what tool require it?

isn't it better to move to a newer version of node? security + performance?

2023-05-08 18:09 UTC, talentlessguy commented
> > wait why do we need 16.12+? what tool require it?
> 
> isn't it better to move to a newer version of node? security + performance?

the "engine" field doesn't move your tools to a newer version, it requires you to use a newer version. The project  runs with no issue on 12.4+ so I'm not sure why an update is needed

2023-05-08 18:49 UTC, aarontravass commented
> > > wait why do we need 16.12+? what tool require it?
> > 
> > 
> > isn't it better to move to a newer version of node? security + performance?
> 
> the "engine" field doesn't move your tools to a newer version, it requires you to use a newer version. The project runs with no issue on 12.4+ so I'm not sure why an update is needed

reverted the versions in package.json

2023-05-08 18:49 UTC, aarontravass commented
> > > wait why do we need 16.12+? what tool require it?
> > 
> > 
> > isn't it better to move to a newer version of node? security + performance?
> 
> the "engine" field doesn't move your tools to a newer version, it requires you to use a newer version. The project runs with no issue on 12.4+ so I'm not sure why an update is needed

reverted the versions in package.json

2023-05-19 20:23 UTC, talentlessguy commented
@aarontravass there's a merge conflict

2023-05-19 20:41 UTC, aarontravass commented
> @aarontravass there's a merge conflict

oops, i missed it. just merged it

2023-05-19 20:41 UTC, merged