fix res.json() to accept non-object input
tinyhttp/tinyhttp pull request #426
Opened 2024-04-02 11:00 UTC by JTBrinkmann

Just like the express.js documentation, the [tinyhttp documentation](https://tinyhttp.v1rtl.site/docs/api/response.html#res-json) says
> Sends a JSON response. This method sends a response (with the correct `Content-Type` header) that is the parameter converted to a JSON string using [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).
>
> The body can be any kind of JSON, including `object`, `array`, `string`, `boolean`, `number`, or `null`.

However, only Objects (incl. Arrays), `null` and `undefined` are currently supported. Also, the current implementation has an undocumented special handling of Strings, simply assuming they are JSON strings instead of using `JSON.stringify()` (as the documentation explicitly says and as express.js does; i would argue: as users would reasonably expect).

In short: neither `res.json(true)` nor `res.json(123)` works yet.

This PR fixes the current implementation to also support inputs of type `boolean` and `number`. It does not remove the special handling of `string` inputs, as this would be a breaking change (though IMO that should be done for the next major version).

As it should pass linter tests, this PR also replaces `any` types. This breaks the signature `res.send(body: string, encoding: BufferEncoding, cb?: () => void)`, which I can only imagine being not much of a big deal.

Only the **send package** is affected.

As a positive side effect, this PR reduces the code size.

2024-04-02 16:23 UTC, aarontravass commented
Please add test cases

2024-06-26 10:26 UTC, talentlessguy requested changes

2024-06-26 10:26 UTC, talentlessguy commented on packages/send/src/json.ts
> -    }
why are you removing `...args`? having `...args` lets you set additional parameters for res.end

2024-06-26 10:40 UTC, closed without merging

2024-06-26 10:41 UTC, talentlessguy commented
I put the fix on master that handles cases when a value is not serializable (such as BigInt for example) and instead sends an empty request